# Generated by Django 4.2.15 on 2024-08-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContacMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'ContacMe',
                'verbose_name_plural': 'ContacMes',
            },
        ),
    ]
