# Generated by Django 4.2.15 on 2024-08-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContacMe',
            new_name='ContactMe',
        ),
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name': 'ContactMe', 'verbose_name_plural': 'ContactMes'},
        ),
    ]
