# Generated by Django 4.2.15 on 2024-08-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
