# Generated by Django 4.2.15 on 2024-08-23 01:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category_menu', '0002_alter_categorymenu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category_menu.categorymenu'),
        ),
    ]
